ALTER PROCEDURE MYTABLE(OUT PROCEDURES TABLE(CUSTOMER NVARCHAR(256),DETAILS NVARCHAR(256)))
AS
BEGIN
	PROCEDURES = SELECT CUSTOMER AS PURCHASER,NAME AS FIRSTNAME FROM PROCEDURES;
END;

CALL MYTABLE();