CREATE PROCEDURE GETNAME(
IN INTAB TABLE(NAME NVARCHAR(20),BLOODGRP NVARCHAR(10),
		DEFAULT NAMES, IN DELIMITER VARCHAR(5) DEFAULT ',',
		OUT OUTTAB TABLE(GETNAME NVARCHAR(30))
	       )
)
AS
BEGIN
	OUTTAB = SELECT BLOODGRP|| :DELIMITER || NAME AS GETNAME FROM :INTAB;
END;