CREATE PROCEDURE CURSOR
LANGUAGE SQLSCRIPT AS
BEGIN
	DECLARE ID BIGINT;
	DECLARE NAME VARCHAR(10);
	DECLARE CURSOR MYCURSOR (AMOUNT BIGINT) FOR
		SELECT ID,NAME FROM MYTABLE WHERE AMOUNT>20000;
	OPEN MYCURSOR(50);
	FETCH MYCURSOR INTO ID,NAME ;
	CLOSE MYCURSOR;
END;