REPORT ZCASESTATEMENT.

DATA TITLE TYPE C LENGTH 15.

TITLE = 'PROGRAMMING'.

CASE TITLE.
	WHEN 'ABAP'.
		WRITE 'THIS IS NOT THE TITLE '.
	WHEN 'TUTORIAL'.
		WRITE 'THIS IS NOT THE TITLE '.
	WHEN 'PROGRAMMING'.
		WRITE 'THIS IS  THE TITLE '.
	WHEN OTHERS.
		WRITE 'NO MATCH'.
ENDCASE.