REPORT ZNESTEDIF.

DATA : A(3) TYPE N VALUE '100',
	B(3) TYPE N VALUE '200',
	C(3) TYPE N VALUE '300'.

IF A LT B.
	WRITE 'A IS LESS THAN B'.
	IF B GT C.
		WRITE / 'B IS GREATER THAN C'.
	ELSE.
		WRITE / 'B IS LESS THAN C'.
	ENDIF.
ENDIF.