REPORT ZRADIOBUTTON.

PARAMETERS ONEPLUS RADIOBUTTON GROUP rad1.

PARAMETERS SAMSUNG RADIOBUTTON GROUP rad1.

PARAMETERS APPLE RADIOBUTTON GROUP rad1.

PARAMETERS NOKIA RADIOBUTTON GROUP rad1 DEFAULT 'X'.